sudo: required
branches:
    only:
        - master
services:
    - docker
before_install:
    - docker build -t $IMAGE .
    - docker run -d -v /usr/share/nginx/html --name site-data $IMAGE
    - docker run -d --volumes-from site-data --name site-server -p 80:80 nginx
script:
    - curl -s -D - http://localhost -o /dev/null | grep "200 OK"
    - curl -s -D - http://localhost | grep "Welcome"
    - wget --spider -e robots=off -r -p http://localhost
deploy:
    provider: script
    script: scripts/deploy.sh
    on:
        branch: master
