on:
  pull_request:
    branches:
    - 'main'

env:
  REGISTRY: "registry.digitalocean.com/bunnymonkey"
  IMAGE_NAME: "mathuin/chryzrose"

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Build image
      run: docker build -t $REGISTRY/$IMAGE_NAME .